export const LOGIN_PAGE = 'LOGIN_PAGE'
export const SIGNUP_PAGE = 'SIGNUP_PAGE'
export const GUEST_PAGE = 'GUEST_PAGE'
export const GUEST_SEARCH_PAGE = 'GUEST_SEARCH_PAGE'
export const GUEST_ACCOUNT_PAGE = 'GUEST_ACCOUNT_PAGE'

export const GUEST_ABOUT_MOVIE_PAGE = 'GUEST_ABOUT_MOVIE_PAGE'
