export const TOP_RATED_FRONT_PIC = "TOP_RATED_FRONT_PIC"
export const TOP_RATED_BACK_PIC = "TOP_RATED_BACK_PIC"
export const TOP_RATED_TITLE = "TOP_RATED_TITLE"
export const TOP_RATED_RATE = "TOP_RATED_RATE"
export const TOP_RATED_GENRE = "TOP_RATED_GENRE"
export const TOP_RATED_OVERVIEW = 'TOP_RATED_OVERVIEW'

export const TOP_RATED_FAILURE = "TOP_RATED_FAILURE" 
export const TOP_RATED_REQUEST = "TOP_RATED_REQUEST"

export const TOP_RATED_INDEX = 'TOP_RATED_INDEX'

export const TOP_RATED_RESET_INDEX = 'TOP_RATED_RESET_INDEX'
