export const MOST_POPULAR_TV_FRONT_PIC = "MOST_POPULAR_TV_FRONT_PIC"
export const MOST_POPULAR_TV_BACK_PIC = "MOST_POPULAR_TV_BACK_PIC"
export const MOST_POPULAR_TV_TITLE = "MOST_POPULAR_TV_TITLE"
export const MOST_POPULAR_TV_RATE = "MOST_POPULAR_TV_RATE"
export const MOST_POPULAR_TV_GENRE = "MOST_POPULAR_TV_GENRE"
export const MOST_POPULAR_TV_OVERVIEW = 'MOST_POPULAR_TV_OVERVIEW'

export const MOST_POPULAR_TV_FAILURE = "MOST_POPULAR_TV_FAILURE" 
export const MOST_POPULAR_TV_REQUEST = "MOST_POPULAR_TV_REQUEST"

export const MOST_POPULAR_TV_INDEX = 'MOST_POPULAR_TV_INDEX'

export const MOST_POPULAR_TV_RESET_INDEX = 'MOST_POPULAR_TV_RESET_INDEX'
