export const CHANGE_MOVIE_SEARCH_TV_FRONT_PIC = "CHANGE_MOVIE_SEARCH_TV_FRONT_PIC"
export const CHANGE_MOVIE_SEARCH_TV_BACK_PIC = "CHANGE_MOVIE_SEARCH_TV_BACK_PIC"
export const CHANGE_MOVIE_SEARCH_TV_TITLE = "CHANGE_MOVIE_SEARCH_TV_TITLE"
export const CHANGE_MOVIE_SEARCH_TV_RATE = "CHANGE_MOVIE_SEARCH_TV_RATE"
export const CHANGE_MOVIE_SEARCH_TV_GENRE = "CHANGE_MOVIE_SEARCH_TV_GENRE"
export const CHANGE_MOVIE_SEARCH_TV_OVERVIEW = 'CHANGE_MOVIE_SEARCH_TV_OVERVIEW'

export const CHANGE_MOVIE_SEARCH_TV_FAILURE = "CHANGE_MOVIE_SEARCH_TV_FAILURE" 
export const CHANGE_MOVIE_SEARCH_TV_REQUEST = "CHANGE_MOVIE_SEARCH_TV_REQUEST"

export const CHANGE_MOVIE_SEARCH_TV_INDEX = 'CHANGE_MOVIE_SEARCH_TV_INDEX'

export const CHANGE_MOVIE_SEARCH_TV_RESET_INDEX = 'CHANGE_MOVIE_SEARCH_TV_RESET_INDEX'
