export const MOST_POPULAR_FRONT_PIC = "MOST_POPULAR_FRONT_PIC"
export const MOST_POPULAR_BACK_PIC = "MOST_POPULAR_BACK_PIC"
export const MOST_POPULAR_TITLE = "MOST_POPULAR_TITLE"
export const MOST_POPULAR_RATE = "MOST_POPULAR_RATE"
export const MOST_POPULAR_GENRE = "MOST_POPULAR_GENRE"
export const MOST_POPULAR_OVERVIEW = 'MOST_POPULAR_OVERVIEW'

export const MOST_POPULAR_FAILURE = "MOST_POPULAR_FAILURE" 
export const MOST_POPULAR_REQUEST = "MOST_POPULAR_REQUEST"

export const MOST_POPULAR_INDEX = 'MOST_POPULAR_INDEX'

export const MOST_POPULAR_RESET_INDEX = 'MOST_POPULAR_RESET_INDEX'
