export const NOW_PLAYING_FRONT_PIC = "NOW_PLAYING_FRONT_PIC"
export const NOW_PLAYING_BACK_PIC = "NOW_PLAYING_BACK_PIC"
export const NOW_PLAYING_TITLE = "NOW_PLAYING_TITLE"
export const NOW_PLAYING_RATE = "NOW_PLAYING_RATE"
export const NOW_PLAYING_GENRE = "NOW_PLAYING_GENRE"
export const NOW_PLAYING_OVERVIEW = 'NOW_PLAYING_OVERVIEW'

export const NOW_PLAYING_FAILURE = "NOW_PLAYING_FAILURE" 
export const NOW_PLAYING_REQUEST = "NOW_PLAYING_REQUEST"

export const NOW_PLAYING_INDEX = 'NOW_PLAYING_INDEX'

export const NOW_PLAYING_RESET_INDEX = 'NOW_PLAYING_RESET_INDEX'
