export const GET_MOVIE_IMG_PIC = "GET_MOVIE_IMG_PIC"
export const GET_MOVIE_IMG_TITLE = "GET_MOVIE_IMG_TITLE"
export const GET_MOVIE_IMG_RATE = "GET_MOVIE_IMG_RATE"
export const GET_MOVIE_IMG_GENRE = "GET_MOVIE_IMG_GENRE"

export const GUEST_TITLE_MOVIE_FAILURE = "GUEST_TITLE_MOVIE_FAILURE" 
export const GUEST_TITLE_MOVIE_REQUEST = "GUEST_TITLE_MOVIE_REQUEST" 

export const GUEST_ANIMATION_STATE = "GUEST_ANIMATION_STATE"
