export const AIRING_TODAY_FRONT_PIC = "AIRING_TODAY_FRONT_PIC"
export const AIRING_TODAY_BACK_PIC = "AIRING_TODAY_BACK_PIC"
export const AIRING_TODAY_TITLE = "AIRING_TODAY_TITLE"
export const AIRING_TODAY_RATE = "AIRING_TODAY_RATE"
export const AIRING_TODAY_GENRE = "AIRING_TODAY_GENRE"
export const AIRING_TODAY_OVERVIEW = 'AIRING_TODAY_OVERVIEW'

export const AIRING_TODAY_FAILURE = "AIRING_TODAY_FAILURE" 
export const AIRING_TODAY_REQUEST = "AIRING_TODAY_REQUEST"

export const AIRING_TODAY_INDEX = 'AIRING_TODAY_INDEX'

export const AIRING_TODAY_RESET_INDEX = 'AIRING_TODAY_RESET_INDEX'
