export const CHANGE_MOVIE_SEARCH_FRONT_PIC = "CHANGE_MOVIE_SEARCH_FRONT_PIC"
export const CHANGE_MOVIE_SEARCH_BACK_PIC = "CHANGE_MOVIE_SEARCH_BACK_PIC"
export const CHANGE_MOVIE_SEARCH_TITLE = "CHANGE_MOVIE_SEARCH_TITLE"
export const CHANGE_MOVIE_SEARCH_RATE = "CHANGE_MOVIE_SEARCH_RATE"
export const CHANGE_MOVIE_SEARCH_GENRE = "CHANGE_MOVIE_SEARCH_GENRE"
export const CHANGE_MOVIE_SEARCH_OVERVIEW = 'CHANGE_MOVIE_SEARCH_OVERVIEW'

export const CHANGE_MOVIE_SEARCH_FAILURE = "CHANGE_MOVIE_SEARCH_FAILURE" 
export const CHANGE_MOVIE_SEARCH_REQUEST = "CHANGE_MOVIE_SEARCH_REQUEST"

export const CHANGE_MOVIE_SEARCH_INDEX = 'CHANGE_MOVIE_SEARCH_INDEX'

export const CHANGE_MOVIE_SEARCH_RESET_INDEX = 'CHANGE_MOVIE_SEARCH_RESET_INDEX'
